import os
import sys
import subprocess
import argparse
from datetime import datetime

def setup_output_dir(scan_type="out_scan"):
    script_dir = os.path.dirname(os.path.abspath(__file__))
    base_out_dir = os.path.abspath(os.path.join(script_dir, "output", "Individual_Scan", scan_type))
    os.makedirs(base_out_dir, exist_ok=True)
    
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    out_dir = os.path.join(base_out_dir, f"results_{timestamp}")
    os.makedirs(out_dir, exist_ok=True)
    return out_dir

ASSESSMENT_FOCUS = [
    "SPF Configuration",
    "DMARC Enforcement",
    "Domain Reputation & Spoofing Risk"
]

def log(msg, level="INFO"):
    colors = {
        "INFO": "\033[94m",   # Blue
        "SUCCESS": "\033[92m",# Green
        "WARN": "\033[93m",   # Yellow
        "ERROR": "\033[91m",  # Red
        "RESET": "\033[0m"    # Reset
    }
    color = colors.get(level, colors["INFO"])
    print(f"{color}[{level}] {msg}{colors['RESET']}")

def run_external_posture_check(out_dir, domain):
    if not domain:
        return
        
    log(f"Starting External Security Posture Assessment on domain '{domain}' via DNS...", "WARN")
    log(f"Assessment Focus: {', '.join(ASSESSMENT_FOCUS)}", "WARN")
    
    posture_out = os.path.join(out_dir, "external_dns_posture.txt")
    
    try:
        with open(posture_out, "w") as f:
            f.write(f"--- EXTERNAL DNS SECURITY POSTURE FOR: {domain} ---\n\n")
            
            # --- SPF Check ---
            f.write("[*] Verifying Primary SPF Record...\n")
            spf_process = subprocess.run(["nslookup", "-type=txt", domain], capture_output=True, text=True)
            spf_lines = [line.strip().replace('"', '') for line in spf_process.stdout.split('\n') if "v=spf1" in line.lower()]
            
            if spf_lines:
                f.write(f"  FOUND RECORD: {spf_lines[0]}\n")
                if "~all" in spf_lines[0]:
                    f.write("  -> RATING: MODERATE (Softfail: '~all' allows delivery but marks as suspicious)\n")
                elif "-all" in spf_lines[0]:
                    f.write("  -> RATING: EXCELLENT (Hardfail: '-all' rejects unauthorized senders perfectly)\n")
                elif "+all" in spf_lines[0] or "?all" in spf_lines[0]:
                    f.write("  -> RATING: CRITICAL RISK (Permissive: explicitly allows unauthorized people to spoof this domain)\n")
            else:
                f.write("  -> RATING: CRITICAL RISK (No SPF Record Found! Domain can be easily spoofed across all registrars.)\n")
            f.write("\n")
            
            # --- DMARC Check ---
            f.write("[*] Verifying DMARC Enforcement Protocols...\n")
            dmarc_domain = f"_dmarc.{domain}"
            dmarc_process = subprocess.run(["nslookup", "-type=txt", dmarc_domain], capture_output=True, text=True)
            dmarc_lines = [line.strip().replace('"', '') for line in dmarc_process.stdout.split('\n') if "v=DMARC1" in line.upper()]
            
            if dmarc_lines:
                f.write(f"  FOUND RECORD: {dmarc_lines[0]}\n")
                if "p=reject" in dmarc_lines[0].lower():
                    f.write("  -> RATING: EXCELLENT (Policy is Reject: absolute highest protection against impersonation)\n")
                elif "p=quarantine" in dmarc_lines[0].lower():
                    f.write("  -> RATING: GOOD (Policy is Quarantine: spoofed emails go safely into spam/junk)\n")
                elif "p=none" in dmarc_lines[0].lower():
                    f.write("  -> RATING: WEAK (Policy is None: DMARC is essentially turned off. It is acting only as a passive monitor.)\n")
            else:
                f.write("  -> RATING: CRITICAL RISK (No DMARC Record Found at all! No protection against exact-domain 'From' spoofing.)\n")
            f.write("\n")
            
            f.write("-----------------------\n")
            f.write("Note: DKIM checks require possessing the exact cryptographic 'selector' generated by the mail registrar, which cannot be blindly queried without extracting headers from an active email received via Phase 2/3.\n")
            
        log(f"External posture assessment successfully completed and parsed.", "SUCCESS")
    except Exception as e:
        log(f"Error executing External DNS checks: {e}", "ERROR")

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Run External DNS Posture Assessment.")
    parser.add_argument("--out-dir", required=False, help="Output directory (auto-generated if not provided)")
    parser.add_argument("--domain", required=True, help="Target domain (e.g., example.com)")
    
    args = parser.parse_args()
    if not args.out_dir:
        args.out_dir = setup_output_dir(scan_type="out_dns_posture")
    else:
        os.makedirs(args.out_dir, exist_ok=True)
        
    run_external_posture_check(args.out_dir, args.domain)
